apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels: 
        app: mysql-operator
        namespace: homework
    spec:
      serviceAccountName: mysql-sa
      containers:
        - name: mysql-operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
          imagePullPolicy: IfNotPresent
      volumes: 
      - name: datastore
        persistentVolumeClaim:
          claimName: pvc-default
