apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: mysql-sa
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-sa-crole
rules:
- apiGroups: ["otus.homework"]
  resources: ["mysqls", "mysqls/status"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["services", "events", "pods", "pods/status", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/status"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-sa-crb
subjects:
- kind: ServiceAccount
  name: mysql-sa
  namespace: homework
roleRef:
  kind: ClusterRole
  name: mysql-sa-crole
