apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-default
  namespace: homework
spec:
  selector:
  storageClassName: "sc-hostpath"
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi