---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yc-kubernetes-network
  namespace: gitops
spec:
  destination:
    namespace: homework
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes-network
    repoURL: 'https://github.com/Kuber-2024-06OTUS/anizhnikov_repo.git'
    targetRevision: kubernetes-network
  project: otus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true