apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus
  namespace: gitops
spec:
  clusterResourceWhitelist:
  - group: '*'  
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - https://github.com/Kuber-2024-08OTUS/anizhnikov_repo.git
  - https://github.com/Kuber-2024-06OTUS/anizhnikov_repo.git