global:
    tolerations:
        - key: "node-role"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"

controller:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: infra
                operator: In
                values: 
                - "true"

dex:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: infra
                operator: In
                values: 
                - "true"

redis:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: infra
                operator: In
                values: 
                - "true"

server:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: infra
                operator: In
                values: 
                - "true"

repoServer:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: infra
                operator: In
                values: 
                - "true"

applicationSet:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: infra
                operator: In
                values: 
                - "true"

notifications:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: infra
                operator: In
                values: 
                - "true"



