apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels: 
    app: {{ .Values.application.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
    name: http
  - port: 9113
    targetPort: 9113
    name: metrics    
  selector:
    app: {{ .Values.application.name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  namespaceSelector:
    any: true