apiVersion: v2
name: lesson07
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: "1.0.1"
dependencies:
- name: redis
  version: 19.6.4
  repository: https://charts.bitnami.com/bitnami

