# Default values for lesson07.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

configMap:
  db:
    given: Andrey
    family: Ni
    village: Likovo
    age: "33"
    state: SU
    year: "2025"
    month: "8"
    day: "40"
    hour: "25"

serviceAccount:
  enable: true
  name: monitoring

storageClass:
  provisioner: "disk-csi-driver.mks.ycloud.io"

pv:
  storage: 
    size: 128Mi
  path: /srv/
  label: "default"

pvc:
  storage:
    request_size: 128Mi

nodeAffinity:
  enable: true
  key: "homework"
  value: "true"


service:
  type: ClusterIP
  port: 8001
  targetPort: 8001

ingress:
  host: homework.otus

image:
  name: nginx
  repository: bxggs/nginx-autoindex
  tag: latest
  init01_name: install 
  init01_repository: busybox
  init01_tag: latest
  init02_name: metrics 
  init02_repository: curlimages/curl
  init02_tag: latest  

application:
  name: nginx
  port: 8001
  path:
    root: /homework
    conf: /conf

deployment:
    nodeSelector: true
    containerPort: 8001
    readinessProbe: true
